name: Webpack Build Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Packages
        run: |
          sudo apt -qq -y update
          sudo apt -qq -y install \
            wget git-core cmake   \
            python3 python3-pip   \
            nodejs npm            \
            libclang-dev

      - name: Install Python Packages
        run: pip3 install clang

      - name: Install Node.js Packages
        run: npm install

      - name: Install Wasi
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk-12.0-linux.tar.gz
          tar xvf wasi-sdk-12.0-linux.tar.gz
          mv wasi-sdk-12.0 wasi

      - name: CMake Build
        run: |
          LOCAL_REPOSITORY_FULLPATH=$(pwd)
          mkdir cpp-lib/bin && cd cpp-lib/bin
          cmake .. \
              -DCMAKE_TOOLCHAIN_FILE=../../wasi/share/cmake/wasi-sdk.cmake \
              -DWASI_SDK_PREFIX="${LOCAL_REPOSITORY_FULLPATH}/wasi" \
              -DCMAKE_C_FLAGS="--sysroot=\"${LOCAL_REPOSITORY_FULLPATH}/wasi/share/wasi-sysroot\"" \
              -DCMAKE_CXX_FLAGS="--sysroot=\"${LOCAL_REPOSITORY_FULLPATH}/wasi/share/wasi-sysroot\""
          make
      
      - name: Run Build
        run: |
          npm run build:tools
          npm run gen-dts
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
